import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <script defer src="http://umami-io0ocwo.138.197.2.213.sslip.io/script.js" data-website-id="1c204560-f1f5-44e5-a422-b523a86cb5ef"></script>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
